### ISSUE TITLE
GRLC api changed, suggest changing the demo link

### ISSUE THREAD

**Issue by Baytars** [geneontology/example-sparql#2]
The original link http://grlc.io/api/geneontology/example-sparql#/ causes error
```
Errors

Parser error on line 12
end of the stream or a document separator is expected
```
```
Unable to render this definition

The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```
I have tested out that this link http://grlc.io/api-git/geneontology/example-sparql/ works without error for me.

**Comment by kltm** [comment]
@Baytars Thank you for letting us know. This is not currently being developed, but we can take a look at what's going on.
Tagging @dougli1sqrd

**Comment by kltm** [comment]
This now seems to be working. Thank you @dougli1sqrd
